// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXWwscFbPas9S6CXu7YkbHYsTKZjhE9sc',
    appId: '1:361900235244:web:8793335b91baacbedac8c9',
    messagingSenderId: '361900235244',
    projectId: 'flutter-multicounter-app',
    authDomain: 'flutter-multicounter-app.firebaseapp.com',
    storageBucket: 'flutter-multicounter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzCJVvYtAY-eRO0SEbnsFAtyL51XMwaBk',
    appId: '1:361900235244:android:bf2af637b7fd30aadac8c9',
    messagingSenderId: '361900235244',
    projectId: 'flutter-multicounter-app',
    storageBucket: 'flutter-multicounter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvAecbDV83aO4bK5q8rG1OnYk2QHK_a9A',
    appId: '1:361900235244:ios:df13953d4f030b56dac8c9',
    messagingSenderId: '361900235244',
    projectId: 'flutter-multicounter-app',
    storageBucket: 'flutter-multicounter-app.appspot.com',
    iosClientId:
        '361900235244-1ajtubcm7v9t7k3f61ubv0eas62nrvoe.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
